#!/usr/bin/env bash
set -euo pipefail

# Configure the interactive shell for the arrive-aml workflow (idempotent)
# - writes ~/.config/arrive-aml/env with the resolved paths (SOT, mirror, venvs)
# - installs an `aml-bootstrap` command that runs scripts/bootstrap.sh from the SOT
# - adds ONE managed block to ~/.bashrc: PATH, env, and a reminder when /mnt was
#   wiped by a VM restart (mirrors/venvs missing -> run `aml-bootstrap --restore`)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/common.sh"

BLOCK_START="# >>> arrive-aml (managed - do not edit, re-run scripts/lib/configure-shell.sh) >>>"
BLOCK_END="# <<< arrive-aml <<<"

write_env_file() {
  local sot_base="$1"
  mkdir -p "$ARRIVE_CONFIG_DIR"
  cat > "$ARRIVE_ENV_FILE" <<ENV
# arrive-aml paths for this user (generated by scripts/lib/configure-shell.sh)
# Edit to override; re-run 'aml-bootstrap' afterwards.
ARRIVE_SOT_BASE="${sot_base}"
MIRROR_BASE="${MIRROR_BASE}"
UV_VENV_ROOT="${UV_VENV_ROOT}"
ARRIVE_UV_CACHE_DIR="${ARRIVE_UV_CACHE_DIR}"
CLAUDE_SKILLS_CLONE_DIR="${CLAUDE_SKILLS_CLONE_DIR}"
ENV
  log_success "Wrote $ARRIVE_ENV_FILE"
}

write_bootstrap_shim() {
  local sot_base="$1"
  mkdir -p "${HOME}/.local/bin"
  cat > "${HOME}/.local/bin/aml-bootstrap" <<SHIM
#!/usr/bin/env bash
# Re-run the arrive-aml VM bootstrap (safe to run any time; use --restore after a VM restart)
exec bash "${sot_base}/arrive-aml/scripts/bootstrap.sh" "\$@"
SHIM
  chmod +x "${HOME}/.local/bin/aml-bootstrap"
  log_success "Installed command: aml-bootstrap"
}

write_bashrc_block() {
  local rc="${HOME}/.bashrc"
  touch "$rc"
  # Remove a previous managed block
  if grep -qF "$BLOCK_START" "$rc"; then
    sed -i "/^$(printf '%s' "$BLOCK_START" | sed 's/[][\/.*^$]/\\&/g')$/,/^$(printf '%s' "$BLOCK_END" | sed 's/[][\/.*^$]/\\&/g')$/d" "$rc"
  fi
  cat >> "$rc" <<'BLOCK'
# >>> arrive-aml (managed - do not edit, re-run scripts/lib/configure-shell.sh) >>>
case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) export PATH="$HOME/.local/bin:$PATH";; esac
[ -f "$HOME/.config/arrive-aml/env" ] && . "$HOME/.config/arrive-aml/env"
# uv cache on the big local disk when it exists (created by aml-bootstrap)
[ -n "${ARRIVE_UV_CACHE_DIR:-}" ] && [ -d "$ARRIVE_UV_CACHE_DIR" ] && export UV_CACHE_DIR="$ARRIVE_UV_CACHE_DIR"
# /mnt is wiped on every VM stop/start: remind to restore mirrors + venvs
if [ -n "${PS1:-}" ] && [ -n "${MIRROR_BASE:-}" ] && [ ! -d "$MIRROR_BASE" ]; then
  printf '\033[1;33m⚠ %s is missing (VM restarted?). Restore mirrors + venvs with:  aml-bootstrap --restore\033[0m\n' "$MIRROR_BASE"
fi
# <<< arrive-aml <<<
BLOCK
  log_success "Updated managed block in ~/.bashrc"
}

configure_shell() {
  log_info "Configuring shell..."
  local sot_base
  if ! sot_base="$(detect_sot_base)"; then
    log_error "Could not determine the SOT base directory (expected ~/cloudfiles/code/Users/<you>/main)."
    log_info "Clone arrive-aml there first, or set ARRIVE_SOT_BASE."
    return 1
  fi
  write_env_file "$sot_base"
  write_bootstrap_shim "$sot_base"
  write_bashrc_block
  log_info "SOT base: $sot_base   mirrors: $MIRROR_BASE   venvs: $UV_VENV_ROOT"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  check_not_root
  configure_shell
fi
